plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'co.custech.calltracker.callhandler'
version = '0.1.0'

android {
  namespace "co.custech.calltracker.callhandler"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
